### ISSUE TITLE
Error with MPI logging 

### ISSUE THREAD

**Issue by ejpaul** [hiddenSymmetries/simsopt#178]
I am running into an error with calling initialize_logging() with mpi=True. This can be seen by running the 1_Simple/logging_example.py, whose output is copied below. 

Running 1_Simple/logger_example.py
==================================
Hello (times 1) from serial job
Hello (times 2) from serial job
Traceback (most recent call last):
  File "/Users/elizabeth/opt/miniconda3/envs/vmec2000_conda/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/Users/elizabeth/opt/miniconda3/envs/vmec2000_conda/lib/python3.8/logging/config.py", line 723, in configure_handler
    if issubclass(klass, logging.handlers.MemoryHandler) and\
TypeError: issubclass() arg 1 must be a class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/1_Simple/logger_example.py", line 25, in <module>
    initialize_logging(mpi=True, filename='mpi.log')
  File "/Users/elizabeth/opt/miniconda3/envs/vmec2000_conda/lib/python3.8/site-packages/simsopt-0.6.1.dev129+gbdf9974-py3.8-macosx-10.9-x86_64.egg/simsopt/util/logging.py", line 45, in initialize_logging
    logging.config.dictConfig(config_dict)
  File "/Users/elizabeth/opt/miniconda3/envs/vmec2000_conda/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/Users/elizabeth/opt/miniconda3/envs/vmec2000_conda/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'mpi_file_handler'

**Comment by mbkumar** [comment]
@ejpaul, I'll take a look into it.
