### ISSUE TITLE
Issues installing SIMSOPT

### ISSUE THREAD

**Issue by abaillod** [hiddenSymmetries/simsopt#190]
Hello,

I am trying to install SIMSOPT on my local machine at SPC and I get some errors. I pulled the latest release (9ae53edc). This is what I did:

1. Created a new, clean virtual environment
```
(simsopt) abaillod@spcpc602:~/simsopt> mkvirtualenv --no-site-package simsopt
```

2. Installed simsopt
```
(simsopt) abaillod@spcpc602:~/simsopt> pip install -e .[MPI,SPEC]
...
Successfully installed Deprecated-1.2.13 absl-py-1.0.0 cached-property-1.5.2 cycler-0.11.0 f90nml-1.3.1 flatbuffers-2.0 h5py-3.1.0 importlib-metadata-4.8.3 jax-0.2.17 jaxlib-0.1.69 kiwisolver-1.3.1 matplotlib-3.3.4 monty-2022.1.12.1 mpi4py-3.1.3 mpmath-1.2.1 nptyping-1.4.4 numpy-1.19.5 opt-einsum-3.3.0 pillow-8.4.0 py-spec-3.0.1 pyoculus-0.1.3 pyparsing-3.0.6 python-dateutil-2.8.2 randomgen-1.21.2 ruamel.yaml-0.17.20 ruamel.yaml.clib-0.2.6 scipy-1.5.4 simsopt-0.6.1.post123+g9ae53edc.d20220119.dirty six-1.16.0 sympy-1.9 typing-extensions-4.0.1 typish-1.9.3 wrapt-1.13.3 zipp-3.6.0
```

3. Install module dataclasses (apparently not installed by point 2.)
```
(simsopt) abaillod@spcpc602:~/simsopt> pip install dataclasses
```

4. Set up python path and try to import simsopt
```
(simsopt) abaillod@spcpc602:~/simsopt> export PYTHONPATH=/home/abaillod/simsopt/src
(simsopt) abaillod@spcpc602:~/simsopt> python
Python 3.6.9 (default, Oct 29 2019, 10:39:36) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import simsopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abaillod/simsopt/src/simsopt/__init__.py", line 13, in <module>
    from ._core import make_optimizable
  File "/home/abaillod/simsopt/src/simsopt/_core/__init__.py", line 1, in <module>
    from .graph_optimizable import Optimizable, make_optimizable
  File "/home/abaillod/simsopt/src/simsopt/_core/graph_optimizable.py", line 398, in <module>
    class Optimizable(ABC_Callable, Hashable, metaclass=OptimizableMeta):
  File "/home/abaillod/simsopt/src/simsopt/_core/graph_optimizable.py", line 776, in Optimizable
    def _get_ancestors(self) -> list[Optimizable]:
TypeError: 'type' object is not subscriptable
```

What is this error message? Did I mess up something in my installation?

Thanks in advance for your help.

**Comment by landreman** [comment]
You might need a more recent version of python, >= 3.7. Does that help?

**Comment by abaillod** [comment]
Thanks for the tip - I will give it a try, once I figure out how to install a new version of python on my machine... I will report here once I could try it!

**Comment by mbkumar** [comment]
The EOL for python 3.6 is 23 Dec 2021. We dropped support for python 3.6 at the beginning/middle of last year.

To my knowledge, mkvirtualenv does not let you choose an alternative version of python. You need to use either miniconda/anaconda to get different versions of python. 

I am closing this.
