### ISSUE TITLE
setuptools_scm LookupError

### ISSUE THREAD

**Issue by zhucaoxiang** [hiddenSymmetries/simsopt#246]
Hi @mbkumar , do you happen to know what causes the following error? We are trying to install SIMSOPT locally. Somehow, the `setuptools_scm` always prints the following error if we just do `python setup.py --version`.  It looks like `setuptools_scm` cannot find the correct version. I am not familiar with `setuptools_scm` at all.

```
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    version = setuptools_scm.get_version(
  File "/home/ustc/anaconda3/envs/python3.8/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 149, in get_version
    _version_missing(config)
  File "/home/ustc/anaconda3/envs/python3.8/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 109, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /home/ustc/simsopt-master/simsopt-master.
```

**Comment by mbkumar** [comment]
Hello Caoxiang,

Did you clone the repo with full history and not just a shallow clone?

**Comment by mbkumar** [comment]
Try to run the below command and check if it helps.

`git fetch --prune --unshallow --tags`
