### ISSUE TITLE
Need help installing simsopt on Marconi

### ISSUE THREAD

**Issue by abaillod** [hiddenSymmetries/simsopt#250]
Hello,

I am trying to compile simsopt on the Marconi cluster from CINECA, and I have some compilation errors. I would appreciate any help!

Since I could compile and run on my local machine using anaconda, I decided to follow the same approach. I want to test some new features I implemented, thus I need to install simsopt with the `pip install -e .` command. I first started by downloading miniconda and installed it:

```
module purge
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh
chmod u+x Miniconda3-py39_4.12.0-Linux-x86_64.sh
./Miniconda3-py39_4.12.0-Linux-x86_64.sh
miniconda3/bin/conda config --set auto_activate_base false
source ~/.bashrc
conda activate base
conda update -n base conda
conda update --all
conda update -c conda-forge --all
```

I then cloned the simsopt repository and installed it:
```
conda deactivate && conda create --name test --no-default-packages && conda activate test
conda install pip cmake ninja
cd simsopt
conda install -c conda-forge --file requirements.txt 
pip install -e .
```

To which I get the (very long) following error message:
```
... (lots of output)
...
    In file included from /usr/include/c++/4.8.2/memory:79:0,
                     from /usr/include/c++/4.8.2/bits/forward_list.h:35,
                     from /usr/include/c++/4.8.2/forward_list:38,
                     from /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/detail/common.h:155,
                     from /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/pytypes.h:12,
                     from /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/cast.h:13,
                     from /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/attr.h:13,
                     from /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/pybind11.h:45,
                     from /marconi/home/userexternal/abaillod/simsopt/src/simsoptpp/python_magneticfield.cpp:1:
    /usr/include/c++/4.8.2/functional: In substitution of ‘template<class _Res, class ... _ArgTypes> template<class _Functor> using _Invoke = decltype (std::__callable_functor(declval<_Functor&>())((declval<_ArgTypes>)()...)) [with _Functor = std::decay<InterpolatedField<T>::InterpolatedField(std::shared_ptr<MagneticField<T> >, InterpolationRule, RangeTriplet, RangeTriplet, RangeTriplet, bool, int, bool, std::function<std::vector<bool>(std::vector<double>, std::vector<double>, std::vector<double>)>) [with T = xt::pytensor; RangeTriplet = std::tuple<double, double, int>]::__lambda531>::type; _Res = std::vector<double>; _ArgTypes = {std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >}]’:
    /usr/include/c++/4.8.2/functional:2334:2:   required by substitution of ‘template<class _Functor> std::function<_Res(_ArgTypes ...)>::_Requires<std::__and_<std::__not_<std::is_same<typename std::decay<_Tp>::type, std::function<_Res(_ArgTypes ...)> > >, std::__or_<std::is_void<_Tp>, std::is_convertible<std::function<_Res(_ArgTypes ...)>::_Invoke<typename std::decay<_Tp>::type>, _Res> > >, std::function<_Res(_ArgTypes ...)>&> std::function<_Res(_ArgTypes ...)>::operator=(_Functor&&) [with _Functor = _Functor; _Res = std::vector<double>; _ArgTypes = {std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >}] [with _Functor = InterpolatedField<T>::InterpolatedField(std::shared_ptr<MagneticField<T> >, InterpolationRule, RangeTriplet, RangeTriplet, RangeTriplet, bool, int, bool, std::function<std::vector<bool>(std::vector<double>, std::vector<double>, std::vector<double>)>) [with T = xt::pytensor; RangeTriplet = std::tuple<double, double, int>]::__lambda531]’
    /marconi/home/userexternal/abaillod/simsopt/src/simsoptpp/magneticfield_interpolated.h:168:29:   required from ‘InterpolatedField<T>::InterpolatedField(std::shared_ptr<MagneticField<T> >, InterpolationRule, RangeTriplet, RangeTriplet, RangeTriplet, bool, int, bool, std::function<std::vector<bool>(std::vector<double>, std::vector<double>, std::vector<double>)>) [with T = xt::pytensor; RangeTriplet = std::tuple<double, double, int>]’
    /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/detail/init.h:61:101:   required from ‘Class* pybind11::detail::initimpl::construct_or_initialize(Args&& ...) [with Class = InterpolatedField<xt::pytensor>; Args = {std::shared_ptr<MagneticField<xt::pytensor> >, InterpolationRule, std::tuple<double, double, int>, std::tuple<double, double, int>, std::tuple<double, double, int>, bool, int, bool, std::function<std::vector<bool, std::allocator<bool> >(std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >)>}; typename std::enable_if<std::is_constructible<_Tp, _Args>::value, int>::type <anonymous> = 0]’
    /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/detail/init.h:175:94:   required from ‘pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<InterpolatedField<xt::pytensor>, std::shared_ptr<InterpolatedField<xt::pytensor> >, MagneticField<xt::pytensor> >; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {std::shared_ptr<MagneticField<xt::pytensor> >, InterpolationRule, std::tuple<double, double, int>, std::tuple<double, double, int>, std::tuple<double, double, int>, bool, int, bool, std::function<std::vector<bool, std::allocator<bool> >(std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >)>}]::__lambda4’
    /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/detail/init.h:174:29:   required from ‘struct pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<InterpolatedField<xt::pytensor>, std::shared_ptr<InterpolatedField<xt::pytensor> >, MagneticField<xt::pytensor> >; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {std::shared_ptr<MagneticField<xt::pytensor> >, InterpolationRule, std::tuple<double, double, int>, std::tuple<double, double, int>, std::tuple<double, double, int>, bool, int, bool, std::function<std::vector<bool, std::allocator<bool> >(std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >)>}]::__lambda4’
    /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/detail/init.h:174:9:   required from ‘static void pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<InterpolatedField<xt::pytensor>, std::shared_ptr<InterpolatedField<xt::pytensor> >, MagneticField<xt::pytensor> >; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {std::shared_ptr<MagneticField<xt::pytensor> >, InterpolationRule, std::tuple<double, double, int>, std::tuple<double, double, int>, std::tuple<double, double, int>, bool, int, bool, std::function<std::vector<bool, std::allocator<bool> >(std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >)>}]’
    /marconi/home/userexternal/abaillod/simsopt/thirdparty/pybind11/include/pybind11/pybind11.h:1296:9:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const pybind11::detail::initimpl::constructor<Args ...>&, const Extra& ...) [with Args = {std::shared_ptr<MagneticField<xt::pytensor> >, InterpolationRule, std::tuple<double, double, int>, std::tuple<double, double, int>, std::tuple<double, double, int>, bool, int, bool, std::function<std::vector<bool, std::allocator<bool> >(std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >)>}; Extra = {}; type_ = InterpolatedField<xt::pytensor>; options = {std::shared_ptr<InterpolatedField<xt::pytensor> >, MagneticField<xt::pytensor>}]’
    /marconi/home/userexternal/abaillod/simsopt/src/simsoptpp/python_magneticfield.cpp:108:180:   required from here
    /usr/include/c++/4.8.2/functional:2181:71: error: use of ‘InterpolatedField<T>::InterpolatedField(std::shared_ptr<MagneticField<T> >, InterpolationRule, RangeTriplet, RangeTriplet, RangeTriplet, bool, int, bool, std::function<std::vector<bool>(std::vector<double>, std::vector<double>, std::vector<double>)>) [with T = xt::pytensor; RangeTriplet = std::tuple<double, double, int>]::__lambda531’ before deduction of ‘auto’
      using _Invoke = decltype(__callable_functor(std::declval<_Functor&>())
                                                                           ^
    /usr/include/c++/4.8.2/functional:2257: confused by earlier errors, bailing out
    Preprocessed source stored into /scratch_local/ccl2Jamt.out file, please attach this to your bugreport.
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/marconi/home/userexternal/abaillod/simsopt/setup.py", line 123, in <module>
        setup(
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
        return run_commands(dist)
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
        dist.run_commands()
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
        self.run_command(cmd)
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
        self.distribution.run_command(command)
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 459, in build_extensions
        self._build_extensions_serial()
      File "/scratch_local/pip-build-env-9wwpijua/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 485, in _build_extensions_serial
        self.build_extension(ext)
      File "/marconi/home/userexternal/abaillod/simsopt/setup.py", line 105, in build_extension
        subprocess.check_call(
      File "/marconi_scratch/userexternal/abaillod/miniconda3/envs/test/lib/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'simsoptpp']' returned non-zero exit status 1.
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
```

In case this is useful, these are the packages I installed in my environment:
```
(test) [abaillod@r000u08l03 simsopt]$  conda list
# packages in environment at /marconi_scratch/userexternal/abaillod/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
abseil-cpp                20211102.0           h27087fc_1    conda-forge
absl-py                   1.1.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.07.19           h06a4308_0  
certifi                   2022.6.15       py310h06a4308_0  
cmake                     3.22.1               h1fce559_0  
deprecated                1.2.13             pyh6c4a22f_0    conda-forge
etils                     0.6.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.4                h295c915_0  
f90nml                    1.4.3              pyhd8ed1ab_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2           py310h92f7908_0    conda-forge
grpc-cpp                  1.46.3               hbd84cd8_2    conda-forge
importlib-metadata        4.11.4          py310hff52083_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
jax                       0.3.15             pyhd8ed1ab_0    conda-forge
jaxlib                    0.3.14          cpu_py310he634034_2    conda-forge
krb5                      1.19.2               hac12032_0  
ld_impl_linux-64          2.38                 h1181459_1  
libblas                   3.9.0           15_linux64_openblas    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libcurl                   7.82.0               h0b77cf5_0  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
liblapack                 3.9.0           15_linux64_openblas    conda-forge
libnghttp2                1.46.0               hce63b2e_0  
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libprotobuf               3.20.1               h6239696_0    conda-forge
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   1.0.3                h7f8727e_2  
libuv                     1.40.0               h7b6447c_0  
libzlib                   1.2.12               h166bdaf_2    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
lz4-c                     1.9.3                h295c915_1  
monty                     2022.4.26          pyhd8ed1ab_0    conda-forge
mpc                       1.2.1                h9f54685_0    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h5eee18b_3  
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
nptyping                  2.2.0              pyhd8ed1ab_0    conda-forge
numpy                     1.23.1          py310h53a5b5f_0    conda-forge
openssl                   1.1.1q               h7f8727e_0  
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pip                       22.1.2          py310h06a4308_0  
pyevtk                    1.5.0              pyh8a188c0_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
python                    3.10.4               h12debd9_0  
python-flatbuffers        2.0                pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
randomgen                 1.23.1          py310hde88566_0    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h7f8727e_1  
rhash                     1.4.1                h3c74f83_1  
ruamel.yaml               0.17.21         py310h5764c6d_1    conda-forge
ruamel.yaml.clib          0.2.6           py310h5764c6d_1    conda-forge
scipy                     1.8.1           py310h7612f91_0    conda-forge
setuptools                61.2.0          py310h06a4308_0  
setuptools-scm            7.0.5              pyhd8ed1ab_0    conda-forge
setuptools_scm            7.0.5                hd8ed1ab_0    conda-forge
sqlite                    3.38.5               hc218d9a_0  
sympy                     1.10.1          py310hff52083_0    conda-forge
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
typish                    1.9.3              pyhd8ed1ab_0    conda-forge
tzdata                    2022a                hda174b7_0  
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.14.1          py310h5764c6d_0    conda-forge
xz                        5.2.5                h7f8727e_1  
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h7f8727e_2  
zstd                      1.5.2                ha4553b6_0
```

**Comment by rogeriojorge** [comment]
Here are my notes to install SIMSOPT on Marconi:

module load git
module load python/3.9.4
module load gnu/6.1.0
module load openmpi/2.1.1--gnu--6.1.0
module load intel/pe-xe-2018--binary
module load intelmpi/2018--binary
module load mkl/2018--binary
module load zlib/1.2.8--gnu--6.1.0
module load szip/2.1--gnu--6.1.0
module load hdf5/1.10.4--intelmpi--2018--binary
module load netcdf/4.6.1--intelmpi--2018--binary
module load netcdff/4.4.4--intelmpi--2018--binary
module load netcdf-cxx4/4.3.0--intelmpi--2018--binary
module load fftw/3.3.7--intelmpi--2018--binary
module load petsc/3.13.3--intelmpi--2018--binary
module load blas/3.8.0--intel--pe-xe-2018--binary
module load scalapack/2.0.2--intelmpi--2018--binary
module load boost/1.66.0--intelmpi--2018--binary

cmake_config_file.json for VMEC2000
{
    "cmake_args": [
           "-DCMAKE_C_COMPILER=mpiicc",
           "-DCMAKE_CXX_COMPILER=mpiicpc",
           "-DCMAKE_Fortran_COMPILER=mpiifort",
           "-DNETCDF_INC_PATH=/cineca/prod/opt/libraries/netcdff/4.4.4/intelmpi--2018--binary/include",
           "-DNETCDF_LIB_PATH=/cineca/prod/opt/libraries/netcdff/4.4.4/intelmpi--2018--binary/lib"
]
}
python setup.py install

Before compiling SIMSOPT and booz_xform (not for VMEC)
export CC=mpicc
export CXX=mpicxx
python setup.py install

**Comment by rogeriojorge** [comment]
Note: VMEC will have a different CC/CXX executable than the one given to SIMSOPT

**Comment by abaillod** [comment]
Thanks!

Question: On zoom, you mentioned you use anaconda; but you don't seem to load the related module in the notes you sent me. Did you install your own version of anaconda? If yes, do you load all these modules once you are in your conda environment?

**Comment by rogeriojorge** [comment]
I installed SIMSOPT with anaconda, using the instructions below. However, I was not able to compile VMEC2000. This is why I ditched ANACONDA and used the instructions above (sorry for not being clear about that)

conda create -n simsopt python=3.8
conda activate simsopt
conda install -c sorland jaxlib
conda install mpi4py h5py randomgen matplotlib scipy Deprecated nptyping sympy monty f90nml pyevtk setuptools_scm f90wrap pybind11 cmake ninja boost gfortran setuptools_scm scalapack scikit-build numpy
(Take f90wrap and randomgen in m100)
(NEED MODULE LOAD gnu/8.3.0 on Marconi)
cd simsopt
python setup.py install

**Comment by abaillod** [comment]
It took me a bit of time but I think I figured out a way to make it work following what you did! Thank you.

For reference, this is what I did:
```bash
# Load python and anaconda (can be added to the ~/.bashrc)
module load python/3.6.4
module load anaconda/2019.10
module load gnu/8.3.0

# Create simsopt environment with python version 3.9
# Attention! python 3.10 leads to some weird dependencies bug?
conda create -n simsopt python=3.9 --no-deps

# Initialize conda with bash interface (only done first time using anaconda)
conda init bash 
source .bashrc 

# Configure environment
conda activate simsopt
conda config --append channels conda-forge # Not sure if this is necessary
conda install jaxlib mpi4py h5py randomgen matplotlib scipy Deprecated nptyping sympy monty f90nml pyevtk setuptools_scm f90wrap pybind11 cmake ninja boost gfortran setuptools_scm scalapack scikit-build numpy ninja
conda install typed-ast>=1.3.0 # I don't know why I need this

# Install simsopt
# I install with pip instead of running python setup.py install
cd simsopt 
pip install -e .[MPI]

# Test installation with
srun ./run_tests
srun -p skl_fua_dbg ./run_tests_mpi
```

I will try know to compile the SPEC python wrappers in the same environment...
