### ISSUE TITLE
Help with Wechsung's PreciseQS setup

### ISSUE THREAD

**Issue by cfe316** [hiddenSymmetries/simsopt#378]
As an exercise in running Simsopt I'm trying to use the CoilsForPreciseQS scripts / [repo](https://github.com/florianwechsung/CoilsForPreciseQS) 
I've tried following Florian's instructions (in a fresh virtual environment)

```zsh
> pyenv virtualenv 3.8 vsimsopt
> pyenv activate vsimsopt
> cd CoilsForPreciseQS
> pip install -e simsopt # seems to work fine
> python
```
```python
Python 3.8.17 (default, Nov  8 2023, 11:59:10)
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import simsopt as sopp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jacob/packages/CoilsForPreciseQS/simsopt/src/simsopt/__init__.py", line 13, in <module>
    from ._core import make_optimizable
  File "/home/jacob/packages/CoilsForPreciseQS/simsopt/src/simsopt/_core/__init__.py", line 1, in <module>
    from .graph_optimizable import Optimizable, make_optimizable
  File "/home/jacob/packages/CoilsForPreciseQS/simsopt/src/simsopt/_core/graph_optimizable.py", line 27, in <module>
    from ..util.types import RealArray, StrArray, BoolArray, Key
  File "/home/jacob/packages/CoilsForPreciseQS/simsopt/src/simsopt/util/types.py", line 15, in <module>
    RealArray = Union[Sequence[Real], NDArray[Float]]
  File "/home/jacob/.pyenv/versions/simsopt/lib/python3.8/site-packages/nptyping/base_meta_classes.py", line 145, in __getitem__
    args = cls._get_item(item)
  File "/home/jacob/.pyenv/versions/simsopt/lib/python3.8/site-packages/nptyping/ndarray.py", line 73, in _get_item
    cls._check_item(item)
  File "/home/jacob/.pyenv/versions/simsopt/lib/python3.8/site-packages/nptyping/ndarray.py", line 109, in _check_item
    raise InvalidArgumentsError(f"Unexpected argument of type {type(item)}.")
nptyping.error.InvalidArgumentsError: Unexpected argument of type <class 'type'>.
>>>
```

I'm getting errors related to typing or `nptyping`. Originally 

Using `git submodule` Florian picked a specific commit of simsopt for his demo.
*

**Comment by cfe316** [comment]
My apologies - I solved this issue but hit the wrong 'open issue' by mistake.
