### ISSUE TITLE
Run failure from mpi group workers skipping objective evaluation

### ISSUE THREAD

**Issue by smiet** [hiddenSymmetries/simsopt#380]
Both `Residue()` and (Boozer) `Quasisymmetry()` contain code to skip evaluation if not an mpi group leader: 

```python
        if (self.boozer.mpi is not None) and (not self.boozer.mpi.proc0_groups):
            logger.info("This proc is skipping Quasisymmetry.J since it is not a group leader.")
            return np.array([])
```

however the leaders results are communicated incorrectly to the group and this causes runs to hang when runs are performed with more than one worker per group. 

[running with more than one worker per group would greatly speed up spec freeboundary optimizations, as the freeboundary calculation can be very time consuming]

Reproduce: run `examples/2_intermediate/eliminate_magnetic_islands.py` and `examples/2_intermediate/QH_fixed_resolution_boozer.py` 

after setting
`mpi =  MpiPartition(2)` (line 28 and line 19 respectively), 

and run with `mpiexec - n >2`

here is the log of this run for `eliminate_magnetic_islands.py` in the latest docker container: 
```
root@d2fa05ddbd90:/simsopt/examples/2_Intermediate# mpiexec -n 2 python eliminate_magnetic_islands.py 
[0] INFO:root:25 Running 2_Intermediate/eliminate_magnetic_islands.py
[0] INFO:root:26 ====================================================
[1] INFO:root:25 Running 2_Intermediate/eliminate_magnetic_islands.py
[1] INFO:root:26 ====================================================
[1] INFO:simsopt.mhd.spec:142 Initializing a SPEC object from file: /simsopt/examples/2_Intermediate/inputs/QH-residues.sp
[0] INFO:simsopt.mhd.spec:142 Initializing a SPEC object from file: /simsopt/examples/2_Intermediate/inputs/QH-residues.sp
readin :            : 
readin :    1413.46 : Igeometry=  3 ; Istellsym=  1 ; Lreflect=  0 ;
readin :            : Lfreebound=  0 ; phiedge=  2.000000000000000E+00 ; curtor=  1.038123580200000E-09 ; curpol=  0.000000000000000E+00 ;
readin :            : gamma=  0.000000000000000E+00 ;
readin :            : Nfp=  4 ; Nvol=  1 ; Mvol=  1 ; Mpol=  9 ; Ntor=  6 ;
readin :            : pscale=  0.00000E+00 ; Ladiabatic= 0 ; Lconstraint=  0 ; mupf: tol,its=  1.00E-12 , 128 ;
readin :            : Lrad = 12,
readin :            : 
readin :    1413.46 : Linitialize=  1 ;LautoinitBn=  1 ; Lzerovac= 0 ; Ndiscrete= 2 ;
readin :            : Nquad=  -1 ; iMpol=  -4 ; iNtor=  -4 ;
readin :            : Lsparse= 0 ; Lsvdiota= 0 ; imethod= 3 ; iorder= 2 ; iprecon= 1 ; iotatol= -1.00000E+00 ;
readin :            : Lextrap= 0 ; Mregular= -1 ; Lrzaxis= 2 ; Ntoraxis= 3 ;
readin :            : 
readin :    1413.46 : LBeltrami= 4 ; Linitgues= 1 ; Lmatsolver= 3 ; LGMRESprec= 1 ; NiterGMRES= 200 ; epsGMRES=  1.00000E-14 ; epsILU=  1.00000E-12 ;
readin :            : 
readin :    1413.46 : Lfindzero= 2 ;
readin :            : escale=  0.00000E+00 ; opsilon=  1.00000E+00 ; pcondense=  4.000 ; epsilon=  1.00000E+00 ; wpoloidal= 1.0000 ; upsilon=  1.00000E+00 ;
readin :            : forcetol=  1.00000E-12 ; c05xmax=  1.00000E-06 ; c05xtol=  1.00000E-12 ; c05factor=  1.00000E-04 ; LreadGF= F ; 
readin :            : mfreeits=   0 ; gBntol=  1.00000E-06 ; gBnbld=  6.66000E-01 ;
readin :            : vcasingeps=  1.00000E-12 ; vcasingtol=  1.00000E-08 ; vcasingits=     8 ; vcasingper=     1 ;
readin :            : 
readin :    1413.46 : odetol=  1.00E-05 ; nPpts=     1 ;
readin :            : LHevalues= F ; LHevectors= F ; LHmatrix= F ; Lperturbed= 0 ; dpp= -1 ; dqq= -1 ; dRZ=  1.00000000E-05 ; Lcheck=  0 ; Ltiming= F ;
readin :            : 
readin :            : CHANGING ANGLE ;
readin :            : myid=  0 ; Rscale= 2.000000000000000E+00 ;
preset :            : myid=  0 ; Mrad= 12 : Lrad= 12,
preset :    1413.46 : LBsequad= F , LBnewton= F , LBlinear= T ;
preset :            : 
preset :    1413.46 : Nquad=  -1 ; mn=  124 ; NGdof=     0 ; NAdof=  1301,
preset :            : 
preset :    1413.46 : Nt=    72 ; Nz=    48 ; Ntz=     3456 ;
[1] INFO:root:43 Initial zs(6,1):  0.0
[1] INFO:root:44 Initial zs(6,2):  0.0
[1] INFO:simsopt.mhd.spec:1113 This proc is skipping Residue.J() since it is not a group leader.
[1] INFO:simsopt.mhd.spec:1113 This proc is skipping Residue.J() since it is not a group leader.
[1] INFO:root:57 Initial residues: None, None
[1] INFO:simsopt.solve.mpi:114 Beginning solve.
[0] INFO:root:43 Initial zs(6,1):  0.0
[0] INFO:root:44 Initial zs(6,2):  0.0
[0] INFO:simsopt.mhd.spec:754 Preparing to run SPEC.
[0] INFO:simsopt.mhd.spec:931 Running SPEC using filename /simsopt/examples/2_Intermediate/inputs/QH-residues_000_000000
readin :            : 
readin :    1413.61 : Igeometry=  3 ; Istellsym=  1 ; Lreflect=  0 ;
readin :            : Lfreebound=  0 ; phiedge=  2.000000000000000E+00 ; curtor=  1.038123580200000E-09 ; curpol=  0.000000000000000E+00 ;
readin :            : gamma=  0.000000000000000E+00 ;
readin :            : Nfp=  4 ; Nvol=  1 ; Mvol=  1 ; Mpol=  9 ; Ntor=  6 ;
readin :            : pscale=  0.00000E+00 ; Ladiabatic= 0 ; Lconstraint=  0 ; mupf: tol,its=  1.00E-12 , 128 ;
readin :            : Lrad = 12,
readin :            : 
readin :    1413.61 : Linitialize=  1 ;LautoinitBn=  1 ; Lzerovac= 0 ; Ndiscrete= 2 ;
readin :            : Nquad=  -1 ; iMpol=  -4 ; iNtor=  -4 ;
readin :            : Lsparse= 0 ; Lsvdiota= 0 ; imethod= 3 ; iorder= 2 ; iprecon= 1 ; iotatol= -1.00000E+00 ;
readin :            : Lextrap= 0 ; Mregular= -1 ; Lrzaxis= 2 ; Ntoraxis= 3 ;
readin :            : 
readin :    1413.61 : LBeltrami= 4 ; Linitgues= 1 ; Lmatsolver= 3 ; LGMRESprec= 1 ; NiterGMRES= 200 ; epsGMRES=  1.00000E-14 ; epsILU=  1.00000E-12 ;
readin :            : 
readin :    1413.61 : Lfindzero= 2 ;
readin :            : escale=  0.00000E+00 ; opsilon=  1.00000E+00 ; pcondense=  4.000 ; epsilon=  1.00000E+00 ; wpoloidal= 1.0000 ; upsilon=  1.00000E+00 ;
readin :            : forcetol=  1.00000E-12 ; c05xmax=  1.00000E-06 ; c05xtol=  1.00000E-12 ; c05factor=  1.00000E-04 ; LreadGF= F ; 
readin :            : mfreeits=   0 ; gBntol=  1.00000E-06 ; gBnbld=  6.66000E-01 ;
readin :            : vcasingeps=  1.00000E-12 ; vcasingtol=  1.00000E-08 ; vcasingits=     8 ; vcasingper=     1 ;
readin :            : 
readin :    1413.61 : odetol=  1.00E-05 ; nPpts=     1 ;
readin :            : LHevalues= F ; LHevectors= F ; LHmatrix= F ; Lperturbed= 0 ; dpp= -1 ; dqq= -1 ; dRZ=  1.00000000E-05 ; Lcheck=  0 ; Ltiming= F ;
readin :            : 
Traceback (most recent call last):
  File "/simsopt/examples/2_Intermediate/eliminate_magnetic_islands.py", line 75, in <module>
    least_squares_mpi_solve(prob, mpi=mpi, grad=True)
  File "/venv/lib/python3.10/site-packages/simsopt/solve/mpi.py", line 199, in least_squares_mpi_solve
    with MPIFiniteDifference(prob.residuals, mpi, abs_step=abs_step,
  File "/venv/lib/python3.10/site-packages/simsopt/_core/finite_difference.py", line 171, in __enter__
    self.mpi_apart()
  File "/venv/lib/python3.10/site-packages/simsopt/_core/finite_difference.py", line 176, in mpi_apart
    self.mpi.apart(lambda mpi, data: self.mpi_leaders_task(),
  File "/venv/lib/python3.10/site-packages/simsopt/util/mpi.py", line 265, in apart
    self.worker_loop(workers_action)
  File "/venv/lib/python3.10/site-packages/simsopt/util/mpi.py", line 243, in worker_loop
    data = self.comm_groups.bcast(data, root=0)
  File "mpi4py/MPI/Comm.pyx", line 1569, in mpi4py.MPI.Comm.bcast
  File "mpi4py/MPI/msgpickle.pxi", line 723, in mpi4py.MPI.PyMPI_bcast
  File "mpi4py/MPI/msgpickle.pxi", line 724, in mpi4py.MPI.PyMPI_bcast
mpi4py.MPI.Exception: Message truncated, error stack:
internal_Bcast(107)...........: MPI_Bcast(buffer=0x7ffd1389baa4, count=1, MPI_INT, 0, comm=0x84000001) failed
MPID_Bcast(95)................: 
MPIDI_POSIX_mpi_bcast(187)....: 
MPIR_Bcast_impl(378)..........: 
MPIR_Bcast_allcomm_auto(317)..: 
MPIR_Bcast_intra_binomial(105): 
MPIDIG_recv_type_init(72).....: Message from rank 0 and tag 2 truncated; 4 bytes received but buffer size is 100
```

removing the skip, and letting all workers run the Residue evaluation fixes this, but is against the spirit. 

I tried to add broadcast statements to the `J()` function, but it was unsucessful. Should something in 'util/mpi.py' be changed?

Any tips are most welcome.

**Comment by smiet** [comment]
After some contemplation; the answer came to me: though workers will skip the evaluation of the function, they need to participate in the shared execution. 

It just needs a [spec,vmec].run() statement.

Preparing a pull request with a unit test in it.
